### ISSUE TITLE
Populate provinces in north-western Russia, central Australia & central Brazil

### ISSUE THREAD

**Issue by Idhrendur** [Idhrendur/paradoxGameConverters#151]
https://forum.paradoxplaza.com/forum/index.php?threads/the-eu4-to-v2-converter-project.707362/page-58#post-17772767

**Comment by derHochmeister** [comment]
Just to know, what does this say?

**Comment by Idhrendur** [comment]
This is an old one, from 2014, actually! And by RageAir, who now works for Paradox.

"Also, a request! Certain areas that were colonised by the start of a normal V2 game are empty in a converted game. Would it be possible to, similar to how we reset provinces in Africa, actually have an option to populate provinces in north-western Russia, central Australia & central Brazil? Perhaps based on nearby national prescence, or in the case of Australia/Brazil on the relative strength of nearby colonial nations? I'm tired of seeing a random nation colonise the north-western part of russia and central Australia, the result is always so ugly!"

**Comment by derHochmeister** [comment]
Is this still a bug? I don't remember it happening.

**Comment by Idhrendur** [comment]
It may have been fixed. There were some really stupid things in the code that tested for the connection to capitals, and they may have caused this back in the day.

I'll close it for now, but keep your eyes peeled in case it needs reopening.

**Comment by kratostatic** [comment]
I think you forgot to close this but no matter.

I can confirm that the Brazil hole is still there, but I'm also kind of fine with that one existing as it's landlocked and so will be filled when/if one of the surrounding countries becomes at least a secondary power.  I'm not so sure about the Russia/Australia ones, I'll check the next time I'm in a converted game.  Although there's a hole even in vanilla Vicky2 Russia as I normally colonise it if I'm playing Sweden/Scandinavia.

**Comment by Idhrendur** [comment]
I don't even know what my former comment was about. I must not have read carefully when I wrote it. Australia is probably the most dramatic case, as the coasts are often colonized in converted games, but most of the interior is unowned.
