### ISSUE TITLE
Invalid stoi argument in log

### ISSUE THREAD

**Issue by kratostatic** [Idhrendur/paradoxGameConverters#311]
When the current version of the converter runs there is a line "[WARNING] Problem inputting date: invalid stoi argument" in the log which appears roughly 4000 times near the top.

This error seems to have no impact on the actual functioning of the converter as far as I can tell from test saves (although there may be hidden issues) but it is very annoying and I can see a lot of people with unrelated problems assuming this is the source of the issue.

**Comment by kratostatic** [comment]
Fixed by #337 and 7a544880228598ce05ef5b29577d359b3c00d2e7 , with thanks to woggy!

**Comment by IohannesIohannium** [comment]
Still happening to me, using the 1.0H converter and a 1.24 save. I've got 2560 lines saying `2018-02-12 15:27:38 [WARNING] Problem inputting date: invalid stoi argument`

**Comment by kratostatic** [comment]
Does the game in question actually convert?  I've found that it does still appear sometimes but it usually indicates an actual problem now.

**Comment by Idhrendur** [comment]
I've been seeing a lot of it with the test save I've been using for the new parser work. IIRC, it's from EU4 provinces, which assume a bunch of things are dates which aren't. In the long term, the new parser stuff should address it. In the short term, try dropping a breakpoint on the line that gives that output to see where it's coming from.

**Comment by IohannesIohannium** [comment]
@kratostatic Conversion goes fine. It's just spammy if I want to see the log.

**Comment by JTPCM** [comment]
The log looks as follows:

2018-02-14 16:04:10    [INFO] Converter version 1.0H
2018-02-14 16:04:10    [INFO] Built Sun Feb 11 22:45:26 2018
2018-02-14 16:04:10   [DEBUG]     Current directory is C:\ ...
2018-02-14 16:04:10    [INFO] Using input file C:\ ...
2018-02-14 16:04:10    [INFO] Reading configuration file
2018-02-14 16:04:10   [DEBUG]     EU4 install path is H:\ ...
2018-02-14 16:04:10   [DEBUG]     Victoria 2 install path is C:\ ...
2018-02-14 16:04:10   [DEBUG]     Victoria 2 documents directory is C:\ ...
2018-02-14 16:04:10    [INFO] Using output name USA
2018-02-14 16:04:10    [INFO] * Importing EU4 save *
2018-02-14 16:04:10    [INFO] Parsing save
2018-02-14 16:04:23    [INFO] Building world
2018-02-14 16:04:23   [DEBUG]     Get EU4 Mods
2018-02-14 16:04:23   [DEBUG]     Get EU4 Mod Directory
2018-02-14 16:04:23   [DEBUG]     EU4 Documents directory is C:\ ...

etc...not important

2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument
2018-02-14 16:04:23 [WARNING] Problem inputting date: invalid stoi argument

Whatever, the most important in the log file are dozens of this WARNINGs 
The question is what's this stoi argument and how is it possible to be fixed (or made, well...valid)
